(()=>{
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const api=()=>localStorage.getItem('amirali_api_url')||window.AMIRALI_API_URL||'';
const session=()=>{try{return JSON.parse(localStorage.getItem('amirali_session')||'null')}catch{return null}};
function addStyle(){if(document.getElementById('am-live-ai-style'))return;const s=document.createElement('style');s.id='am-live-ai-style';s.textContent='.am-live-ai{position:fixed;right:18px;bottom:78px;z-index:10080;border:0;border-radius:18px;padding:12px 16px;background:linear-gradient(135deg,#00c9a7,#4f7cff,#ff5fa2);color:#fff;font-weight:900;box-shadow:0 12px 35px #0008;cursor:pointer}.am-live-ai-box{position:fixed;right:18px;bottom:132px;z-index:10081;width:min(430px,calc(100vw - 36px));max-height:70vh;overflow:auto;background:#0b1628;color:#fff;border:1px solid #ffffff18;border-radius:22px;padding:16px;box-shadow:0 30px 90px #000b;font-family:Vazirmatn,sans-serif}.am-live-ai-head{display:flex;justify-content:space-between;align-items:center}.am-live-ai-close{border:0;background:#ffffff10;color:#fff;border-radius:9px;padding:7px}.am-live-ai-msg{padding:10px 12px;border-radius:13px;background:#12253a;margin:7px 0;line-height:1.8}.am-live-ai-user{background:linear-gradient(135deg,#087d9c,#5546a8)}.am-live-ai-row{display:flex;gap:7px}.am-live-ai-row input{flex:1;border:1px solid #ffffff18;background:#07101d;color:#fff;border-radius:11px;padding:11px}.am-live-ai-row button{border:0;border-radius:11px;background:#21d4b2;padding:10px 14px;font-weight:900}.am-live-ai-config{font-size:11px;color:#8feadd;margin:5px 0 10px}.am-live-ai-health{font-size:11px;color:#ffd166}';document.head.appendChild(s)}
async function ask(msg){const base=api().replace(/\/$/,'');if(!base)throw new Error('API_NOT_CONFIGURED');const r=await fetch(base+'/api/ai/chat',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify({message:msg})});const d=await r.json();if(!r.ok)throw new Error(d.message||'AI_ERROR');return d.answer}
function fallback(msg){if(/پرداخت|فیش/.test(msg))return 'پرداخت و فیش را از مسیر سفارش انجام بده. بعد از تأیید مدیر، دسترسی دوره فعال می‌شود.';if(/کلاس|meet|الوکام/i.test(msg))return 'کلاس فقط در زمان تعیین‌شده و برای دوره‌ای که دسترسی آن تأیید شده قابل ورود است.';if(/تکلیف|نمره/.test(msg))return 'تکلیف مربوط به همان دوره است و نمره مدیر از ۵ ثبت می‌شود.';if(/باگ|خطا|کار نمی/.test(msg))return 'برای عیب‌یابی دقیق، API سرور را وصل کن تا دستیار بتواند وضعیت سرویس را بررسی کند.';return 'من آماده‌ام کمک کنم. برای هوش مصنوعی کامل، API سرور باید تنظیم شده باشد.'}
async function open(){let box=document.querySelector('.am-live-ai-box');if(box){box.remove();return}box=document.createElement('div');box.className='am-live-ai-box';const isAdmin=session()?.role==='admin';box.innerHTML=`<div class="am-live-ai-head"><div><b>${isAdmin?'🤖 AI مدیر':'✨ دستیار هوشمند'}</b><div class="am-live-ai-config">${api()?'🟢 سرور متصل':'🟡 سرور هنوز متصل نیست'}</div></div><button class="am-live-ai-close">✕</button></div><div class="am-live-ai-health" id="am-ai-health"></div><div class="am-live-ai-msg">سلام 👋 مشکل یا سؤال خودت را بنویس.</div><div id="am-ai-log"></div><div class="am-live-ai-row"><input id="am-ai-input" placeholder="مثلاً چرا دوره فعال نشده؟"><button id="am-ai-send">ارسال</button></div>`;document.body.appendChild(box);const log=box.querySelector('#am-ai-log'),input=box.querySelector('#am-ai-input');box.querySelector('.am-live-ai-close').onclick=()=>box.remove();const send=async()=>{const v=input.value.trim();if(!v)return;log.insertAdjacentHTML('beforeend',`<div class="am-live-ai-msg am-live-ai-user">${esc(v)}</div>`);input.value='';const m=document.createElement('div');m.className='am-live-ai-msg';m.textContent='در حال بررسی…';log.appendChild(m);try{m.textContent=await ask(v)}catch(e){m.textContent=fallback(v)}log.scrollTop=log.scrollHeight};box.querySelector('#am-ai-send').onclick=send;input.addEventListener('keydown',e=>{if(e.key==='Enter')send()});if(api()){try{const r=await fetch(api().replace(/\/$/,'')+'/api/health');const h=await r.json();box.querySelector('#am-ai-health').textContent=h.ai?'🤖 هوش مصنوعی فعال است':'⚠️ سرور وصل است ولی کلید هوش مصنوعی تنظیم نشده'}catch{box.querySelector('#am-ai-health').textContent='⚠️ سرور پاسخ نمی‌دهد'}}}
function mount(){addStyle();document.querySelectorAll('.am-ai-fab').forEach(x=>x.remove());const b=document.createElement('button');b.className='am-live-ai';b.textContent=session()?.role==='admin'?'🤖 دستیار مدیر':'✨ دستیار هوشمند';b.onclick=open;document.body.appendChild(b)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
