(() => {
  const CARD='6219-8619-5696-0073',OWNER='امیرعلی رضی خادمی',BANK='بلو بانک';
  const nf=n=>Number(n||0).toLocaleString('fa-IR');
  const isAdmin=()=>/ADMIN CONTROL CENTER|کنترل مدیریت|محصولات و موجودی/.test(document.body?.innerText||'')||localStorage.getItem('amirali_role')==='admin';
  const cartTotal=()=>{try{const c=JSON.parse(localStorage.getItem('amirali_cart')||'[]');return c.reduce((s,i)=>s+Number(i.price||0)*Number(i.quantity||1),0)}catch{return 0}};
  const css=`.am-payment-fab{position:fixed;left:18px;bottom:22px;z-index:9998;border:0;border-radius:18px;padding:13px 17px;background:linear-gradient(135deg,#18b9ef,#7257ed);color:#fff;font:800 14px Vazirmatn,sans-serif;box-shadow:0 14px 40px #0007;cursor:pointer}.am-payment-overlay{position:fixed;inset:0;z-index:9999;background:#020817cc;backdrop-filter:blur(10px);display:none;align-items:center;justify-content:center;padding:18px}.am-payment-overlay.open{display:flex}.am-payment-box{width:min(560px,100%);max-height:92vh;overflow:auto;background:linear-gradient(145deg,#0d2036,#091426);border:1px solid #ffffff18;border-radius:24px;padding:24px;color:#eef6ff;font-family:Vazirmatn,sans-serif;box-shadow:0 30px 90px #000b}.am-payment-head{display:flex;justify-content:space-between;align-items:center}.am-payment-head h2{margin:0}.am-close{border:0;background:#ffffff0d;color:#fff;border-radius:10px;width:38px;height:38px;font-size:20px}.am-card{margin:18px 0;padding:20px;border-radius:20px;background:linear-gradient(135deg,#173c5b,#30205b)}.am-card-number{direction:ltr;text-align:center;font:900 22px monospace;letter-spacing:1px;margin:13px 0}.am-owner,.am-bank{text-align:center;font-weight:800}.am-bank{color:#70e0ff;font-size:12px;margin-top:5px}.am-copy{display:block;margin:13px auto 0;border:1px solid #ffffff20;background:#ffffff10;color:#fff;padding:8px 13px;border-radius:10px}.am-payment-box label{display:block;margin:15px 0 7px;color:#adc0d5;font-size:13px}.am-payment-box input{width:100%;box-sizing:border-box;padding:12px;border:1px solid #ffffff16;background:#050e1d;color:#fff;border-radius:12px}.am-exact{padding:14px;border-radius:14px;background:#18c99b18;border:1px solid #18c99b33;color:#8ff0c9;font-weight:900;font-size:16px}.am-payment-submit{width:100%;margin-top:16px;border:0;border-radius:13px;padding:13px;background:linear-gradient(135deg,#20c3f2,#725be8);color:#fff;font-weight:900}.am-payment-note{color:#849ab4;font-size:12px;line-height:1.8}.am-payment-status{margin-top:13px;padding:12px;border-radius:12px;background:#13c77b18;color:#72e5b1;display:none}.am-payment-preview{max-width:100%;max-height:190px;display:none;margin-top:10px;border-radius:12px}`;
  const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
  const fab=document.createElement('button');fab.className='am-payment-fab';fab.textContent='💳 پرداخت و بارگذاری فیش';
  const overlay=document.createElement('div');overlay.className='am-payment-overlay';const total=cartTotal();overlay.innerHTML=`<div class="am-payment-box"><div class="am-payment-head"><h2>پرداخت سفارش</h2><button class="am-close">×</button></div><div class="am-exact">💰 مبلغ دقیق قابل پرداخت: ${nf(total)} تومان</div><div class="am-card"><div style="color:#a9c0d8;font-size:12px">شماره کارت مقصد</div><div class="am-card-number">${CARD}</div><div class="am-owner">${OWNER}</div><div class="am-bank">${BANK}</div><button class="am-copy" type="button">📋 کپی شماره کارت</button></div><p class="am-payment-note">مبلغ واریزی باید دقیقاً با مبلغ سفارش برابر باشد. پس از ارسال فیش، سفارش تا تأیید مدیر در حالت «در انتظار بررسی» می‌ماند.</p><label>مبلغ واریزی</label><input class="am-amount" type="number" value="${total||''}" min="0"><label>فیش واریزی</label><input class="am-file" type="file" accept="image/*,.pdf"><img class="am-payment-preview"><button class="am-payment-submit">ثبت فیش واریزی</button><div class="am-payment-status"></div></div>`;
  document.body.append(fab,overlay);const close=()=>overlay.classList.remove('open');fab.onclick=()=>overlay.classList.add('open');overlay.querySelector('.am-close').onclick=close;
  const copy=overlay.querySelector('.am-copy');copy.onclick=async()=>{try{await navigator.clipboard.writeText(CARD.replaceAll('-',''));copy.textContent='✓ کپی شد'}catch{}};
  const file=overlay.querySelector('.am-file'),preview=overlay.querySelector('.am-payment-preview');file.onchange=()=>{const f=file.files?.[0];if(f&&f.type.startsWith('image/')){preview.src=URL.createObjectURL(f);preview.style.display='block'}};
  overlay.querySelector('.am-payment-submit').onclick=()=>{const amount=Number(overlay.querySelector('.am-amount').value),f=file.files?.[0],expected=cartTotal();if(!f)return alert('لطفاً فیش را انتخاب کنید.');if(expected&&amount!==expected)return alert(`مبلغ واریزی باید دقیقاً ${nf(expected)} تومان باشد.`);const receipt={id:Date.now(),amount,fileName:f.name,createdAt:new Date().toISOString(),status:'slip_uploaded',expectedAmount:expected};localStorage.setItem('amirali_last_receipt',JSON.stringify(receipt));const st=overlay.querySelector('.am-payment-status');st.textContent=`✓ فیش ثبت شد — مبلغ دقیق ${nf(amount)} تومان — در انتظار تأیید مدیر`;st.style.display='block'};
  const hide=()=>{if(isAdmin()){fab.remove();overlay.remove();return}setTimeout(()=>{if(isAdmin()){fab.remove();overlay.remove()}},1200)};hide();new MutationObserver(hide).observe(document.body,{childList:true,subtree:true});
})();
