import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import pg from 'pg';
import fs from 'fs';
import path from 'path';
const { Pool } = pg;
const app = express();
const PORT = Number(process.env.PORT || 5000);
const JWT_SECRET = process.env.JWT_SECRET || 'CHANGE_ME_IN_PRODUCTION';
const ADMIN_USER = process.env.ADMIN_USER || 'amiralirazi1391';
const ADMIN_PHONE = process.env.ADMIN_PHONE || '09364601110';
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || 'CHANGE_ME';
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || '';
const OPENAI_MODEL = process.env.OPENAI_MODEL || 'gpt-5.6-luna';
const pool = process.env.DATABASE_URL ? new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='false'?false:{rejectUnauthorized:false}}) : null;
app.use(cors({origin:process.env.FRONTEND_URL?process.env.FRONTEND_URL.split(','):true,credentials:true}));
app.use(express.json({limit:'8mb'}));
app.use(cookieParser());
const uploadDir=path.resolve('uploads');fs.mkdirSync(uploadDir,{recursive:true});
const upload=multer({dest:uploadDir,limits:{fileSize:20*1024*1024}});
async function db(sql,params=[]){if(!pool)throw new Error('DATABASE_URL is not configured');return pool.query(sql,params)}
async function initDb(){if(!pool)return;await db(`
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,first_name TEXT NOT NULL,last_name TEXT NOT NULL,username TEXT UNIQUE NOT NULL,phone TEXT NOT NULL,alt_phone TEXT,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS products(id SERIAL PRIMARY KEY,title TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,description TEXT NOT NULL,price INTEGER NOT NULL,type TEXT NOT NULL,category TEXT NOT NULL,image_url TEXT,digital_asset_url TEXT,stock INTEGER NOT NULL DEFAULT 0,related_kit_ids JSONB DEFAULT '[]');
CREATE TABLE IF NOT EXISTS orders(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id),total_amount INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending_payment',created_at TIMESTAMPTZ DEFAULT now(),items JSONB DEFAULT '[]');
CREATE TABLE IF NOT EXISTS shipping_addresses(id SERIAL PRIMARY KEY,order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,full_name TEXT NOT NULL,phone TEXT NOT NULL,postal_code TEXT NOT NULL,address TEXT NOT NULL,floor TEXT,unit TEXT,ring_bell TEXT);
CREATE TABLE IF NOT EXISTS payment_receipts(id SERIAL PRIMARY KEY,order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,receipt_image_url TEXT NOT NULL,ai_detected_amount INTEGER,ai_card_match BOOLEAN,admin_approved BOOLEAN NOT NULL DEFAULT false,created_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS course_lessons(id SERIAL PRIMARY KEY,product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,title TEXT NOT NULL,description TEXT,video_url TEXT,unlock_date TIMESTAMPTZ,sort_order INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS enrollments(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,status TEXT NOT NULL DEFAULT 'active',created_at TIMESTAMPTZ DEFAULT now(),UNIQUE(user_id,product_id));
CREATE TABLE IF NOT EXISTS live_classes(id SERIAL PRIMARY KEY,product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,title TEXT NOT NULL,scheduled_at TIMESTAMPTZ NOT NULL,meeting_url TEXT NOT NULL,platform TEXT NOT NULL DEFAULT 'google_meet',is_active BOOLEAN NOT NULL DEFAULT true);
CREATE TABLE IF NOT EXISTS assignments(id SERIAL PRIMARY KEY,product_id INTEGER REFERENCES products(id) ON DELETE CASCADE,title TEXT NOT NULL,description TEXT,deadline TIMESTAMPTZ,max_grade NUMERIC(3,2) NOT NULL DEFAULT 5);
CREATE TABLE IF NOT EXISTS assignment_submissions(id SERIAL PRIMARY KEY,assignment_id INTEGER REFERENCES assignments(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,file_url TEXT NOT NULL,student_note TEXT,admin_grade NUMERIC(3,2),admin_feedback TEXT,submitted_at TIMESTAMPTZ DEFAULT now());
CREATE TABLE IF NOT EXISTS app_settings(key TEXT PRIMARY KEY,value JSONB NOT NULL DEFAULT '{}',updated_at TIMESTAMPTZ DEFAULT now());`);
const e=await db('SELECT id FROM users WHERE username=$1',[ADMIN_USER]);if(!e.rowCount){const hash=await bcrypt.hash(ADMIN_PASSWORD,12);await db('INSERT INTO users(first_name,last_name,username,phone,password_hash,role) VALUES($1,$2,$3,$4,$5,$6)',['امیرعلی','رضی خادمی',ADMIN_USER,ADMIN_PHONE,hash,'admin'])}}
function auth(req,res,next){try{req.user=jwt.verify(req.cookies.token||'',JWT_SECRET);next()}catch{res.status(401).json({message:'نیاز به ورود دارید'})}}
function admin(req,res,next){if(req.user?.role!=='admin'||req.user.username!==ADMIN_USER)return res.status(403).json({message:'دسترسی مدیر مجاز نیست'});next()}
function publicUser(u){return{id:u.id,firstName:u.first_name,lastName:u.last_name,username:u.username,phone:u.phone,altPhone:u.alt_phone,role:u.role}}
app.get('/api/health',async(_req,res)=>{try{if(pool)await db('SELECT 1');res.json({ok:true,database:!!pool,ai:!!OPENAI_API_KEY,time:new Date().toISOString()})}catch(e){res.status(503).json({ok:false,database:false,ai:!!OPENAI_API_KEY,error:e.message})}});
app.post('/api/auth/register',async(req,res)=>{try{const{firstName,lastName,username,phone,altPhone,password,confirmPassword}=req.body;if(!/^[\u0600-\u06FF\s]+$/.test(firstName||'')||!/^[\u0600-\u06FF\s]+$/.test(lastName||''))return res.status(400).json({message:'نام و نام خانوادگی باید فارسی باشند'});if(!/^[a-zA-Z0-9_]+$/.test(username||''))return res.status(400).json({message:'نام کاربری فقط انگلیسی باشد'});if(!/^09[0-9]{9}$/.test(phone||''))return res.status(400).json({message:'لطفاً شماره تماس خود را به درستی وارد نمایید'});if((password||'').length<8||password!==confirmPassword)return res.status(400).json({message:'رمز عبور نامعتبر است'});const hash=await bcrypt.hash(password,12);const r=await db('INSERT INTO users(first_name,last_name,username,phone,alt_phone,password_hash,role) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[firstName,lastName,username,phone,altPhone||null,hash,'user']);res.status(201).json({user:publicUser(r.rows[0])})}catch(e){if(e.code==='23505')return res.status(409).json({message:'این نام کاربری قبلاً انتخاب شده است'});res.status(500).json({message:'خطای سرور',detail:e.message})}});
app.post('/api/auth/login',async(req,res)=>{try{const r=await db('SELECT * FROM users WHERE username=$1',[req.body.username]);const u=r.rows[0];if(!u||!(await bcrypt.compare(req.body.password,u.password_hash)))return res.status(401).json({message:'نام کاربری یا رمز عبور اشتباه است'});const token=jwt.sign({id:u.id,username:u.username,role:u.role},JWT_SECRET,{expiresIn:'7d'});res.cookie('token',token,{httpOnly:true,sameSite:'none',secure:true,maxAge:7*864e5});res.json({user:publicUser(u)})}catch(e){res.status(500).json({message:'خطای سرور',detail:e.message})}});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('token',{sameSite:'none',secure:true});res.json({ok:true})});
app.get('/api/products',async(_req,res)=>{try{res.json((await db('SELECT * FROM products ORDER BY id DESC')).rows)}catch(e){res.status(503).json({message:'پایگاه داده متصل نیست',detail:e.message})}});
app.get('/api/me',auth,async(req,res)=>res.json({user:publicUser((await db('SELECT * FROM users WHERE id=$1',[req.user.id])).rows[0])}));
app.post('/api/orders',auth,async(req,res)=>{try{const{items=[],address}=req.body;const total=items.reduce((s,i)=>s+Number(i.price||0)*Number(i.quantity||1),0);const o=await db('INSERT INTO orders(user_id,total_amount,status,items) VALUES($1,$2,$3,$4) RETURNING *',[req.user.id,total,'pending_payment',JSON.stringify(items)]);if(address)await db('INSERT INTO shipping_addresses(order_id,full_name,phone,postal_code,address,floor,unit,ring_bell) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[o.rows[0].id,address.fullName,address.phone,address.postalCode,address.address,address.floor||null,address.unit||null,address.ringBell||null]);res.json(o.rows[0])}catch(e){res.status(500).json({message:'ثبت سفارش ناموفق بود',detail:e.message})}});
app.post('/api/orders/:id/receipt',auth,upload.single('receipt'),async(req,res)=>{try{const o=await db('SELECT * FROM orders WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(!o.rowCount)return res.sendStatus(404);const url=req.file?`/uploads/${req.file.filename}`:'';await db('INSERT INTO payment_receipts(order_id,receipt_image_url) VALUES($1,$2)',[req.params.id,url]);const r=await db('UPDATE orders SET status=$1 WHERE id=$2 RETURNING *',['slip_uploaded',req.params.id]);res.json(r.rows[0])}catch(e){res.status(500).json({message:'آپلود فیش ناموفق بود',detail:e.message})}});
app.use('/uploads',express.static(uploadDir));
app.get('/api/admin/orders',auth,admin,async(_req,res)=>res.json((await db(`SELECT o.*,u.username,u.phone,s.full_name,s.postal_code,s.address,s.floor,s.unit,s.ring_bell FROM orders o JOIN users u ON u.id=o.user_id LEFT JOIN shipping_addresses s ON s.order_id=o.id ORDER BY o.id DESC`)).rows));
app.post('/api/admin/orders/:id/approve',auth,admin,async(req,res)=>{const r=await db('UPDATE orders SET status=$1 WHERE id=$2 RETURNING *',['approved',req.params.id]);if(!r.rowCount)return res.sendStatus(404);for(const i of(r.rows[0].items||[])){const p=await db('SELECT id FROM products WHERE id=$1',[i.productId]);if(p.rowCount)await db(`INSERT INTO enrollments(user_id,product_id,status) VALUES($1,$2,'active') ON CONFLICT(user_id,product_id) DO UPDATE SET status='active'`,[r.rows[0].user_id,p.rows[0].id])}await db('UPDATE payment_receipts SET admin_approved=true WHERE order_id=$1',[req.params.id]);res.json(r.rows[0])});
app.post('/api/admin/orders/:id/reject',auth,admin,async(req,res)=>res.json((await db('UPDATE orders SET status=$1 WHERE id=$2 RETURNING *',['rejected',req.params.id])).rows[0]));
app.get('/api/admin/users',auth,admin,async(_req,res)=>res.json((await db('SELECT id,first_name,last_name,username,phone,alt_phone,role,created_at FROM users ORDER BY id DESC')).rows));
app.get('/api/admin/products',auth,admin,async(_req,res)=>res.json((await db('SELECT * FROM products ORDER BY id DESC')).rows));
app.post('/api/admin/products',auth,admin,async(req,res)=>{const p=req.body;const r=await db('INSERT INTO products(title,slug,description,price,type,category,image_url,digital_asset_url,stock,related_kit_ids) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[p.title,p.slug||`product-${Date.now()}`,p.description||'',Number(p.price||0),p.type||'physical_hardware',p.category||'robotics',p.imageUrl||null,p.digitalAssetUrl||null,Number(p.stock||0),JSON.stringify(p.relatedKitIds||[])]);res.json(r.rows[0])});
app.get('/api/admin/classes',auth,admin,async(_req,res)=>res.json((await db('SELECT * FROM live_classes ORDER BY scheduled_at DESC')).rows));
app.post('/api/admin/classes',auth,admin,async(req,res)=>{const c=req.body;const r=await db('INSERT INTO live_classes(product_id,title,scheduled_at,meeting_url,platform,is_active) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[c.productId,c.title,c.scheduledAt,c.meetingUrl,c.platform||'google_meet',c.isActive!==false]);res.json(r.rows[0])});
app.get('/api/courses/:id/lessons',auth,async(req,res)=>{const e=await db('SELECT 1 FROM enrollments WHERE user_id=$1 AND product_id=$2 AND status=$3',[req.user.id,req.params.id,'active']);if(!e.rowCount&&req.user.role!=='admin')return res.status(403).json({message:'دسترسی این دوره فعال نشده است'});res.json((await db('SELECT id,title,description,video_url,unlock_date,sort_order FROM course_lessons WHERE product_id=$1 ORDER BY sort_order',[req.params.id])).rows.map(l=>({...l,locked:l.unlock_date&&new Date(l.unlock_date)>new Date()})))});
app.get('/api/admin/assignments',auth,admin,async(_req,res)=>res.json((await db('SELECT * FROM assignments ORDER BY id DESC')).rows));
app.post('/api/admin/assignments',auth,admin,async(req,res)=>{const a=req.body;const r=await db('INSERT INTO assignments(product_id,title,description,deadline,max_grade) VALUES($1,$2,$3,$4,5) RETURNING *',[a.productId,a.title,a.description||'',a.deadline||null]);res.json(r.rows[0])});
app.get('/api/admin/submissions',auth,admin,async(_req,res)=>res.json((await db('SELECT s.*,a.title AS assignment_title,u.username FROM assignment_submissions s JOIN assignments a ON a.id=s.assignment_id JOIN users u ON u.id=s.user_id ORDER BY s.id DESC')).rows));
app.post('/api/admin/submissions/:id/grade',auth,admin,async(req,res)=>{const grade=Number(req.body.grade);if(grade<0||grade>5)return res.status(400).json({message:'نمره باید بین ۰ تا ۵ باشد'});res.json((await db('UPDATE assignment_submissions SET admin_grade=$1,admin_feedback=$2 WHERE id=$3 RETURNING *',[grade,req.body.feedback||'',req.params.id])).rows[0])});
app.post('/api/ai/chat',auth,async(req,res)=>{if(!OPENAI_API_KEY)return res.status(503).json({message:'دستیار هوشمند هنوز به API متصل نشده است. OPENAI_API_KEY را در سرور تنظیم کنید.'});try{const role=req.user.role==='admin'?'مدیر سامانه':'کاربر سامانه';const prompt=`تو دستیار هوشمند پلتفرم امیرعلی هستی. نقش کاربر: ${role}. به فارسی پاسخ بده. راهکارهای دقیق و کوتاه برای مشکلات سایت، خرید، دوره، کلاس آنلاین و تکالیف بده. درباره وضعیت واقعی داده‌ها فقط بر اساس داده‌ای که در متن آمده صحبت کن و چیزی را حدس نزن. برای مدیر، مراحل عیب‌یابی امن پیشنهاد بده و هرگز درخواست رمز یا کلید مخفی نکن.\n\nسؤال کاربر:\n${String(req.body.message||'').slice(0,6000)}`;const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${OPENAI_API_KEY}`},body:JSON.stringify({model:OPENAI_MODEL,input:prompt,max_output_tokens:700})});const data=await response.json();if(!response.ok)return res.status(response.status).json({message:data?.error?.message||'خطا در سرویس هوش مصنوعی'});const text=data.output_text||data.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'پاسخی دریافت نشد.';res.json({answer:text,model:OPENAI_MODEL})}catch(e){res.status(500).json({message:'ارتباط با هوش مصنوعی ناموفق بود',detail:e.message})}});
app.get('/api/admin/health',auth,admin,async(_req,res)=>{try{const tables=['users','products','orders','course_lessons','enrollments','live_classes','assignments','assignment_submissions','payment_receipts'];const out={};for(const t of tables)out[t]=Number((await db(`SELECT COUNT(*)::int AS n FROM ${t}`)).rows[0].n);res.json({ok:true,database:true,counts:out,ai:!!OPENAI_API_KEY})}catch(e){res.status(503).json({ok:false,database:false,ai:!!OPENAI_API_KEY,error:e.message})}});
initDb().then(()=>app.listen(PORT,()=>console.log(`AmirAli API listening on ${PORT}`))).catch(e=>{console.error(e);process.exit(1)});
