import fs from 'fs';

// Central persistence, student documents, exact payment details, digital assets and course video uploads.
const sourcePath = new URL('./index.js', import.meta.url);
let source = fs.readFileSync(sourcePath, 'utf8');
const featureRoutes = `
if(pool) await db(\`CREATE TABLE IF NOT EXISTS digital_assets(id SERIAL PRIMARY KEY,product_id INTEGER UNIQUE REFERENCES products(id) ON DELETE CASCADE,file_url TEXT,original_name TEXT,file_size BIGINT,asset_kind TEXT NOT NULL,source_code TEXT,created_at TIMESTAMPTZ DEFAULT now()); CREATE TABLE IF NOT EXISTS student_documents(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,file_url TEXT NOT NULL,original_name TEXT NOT NULL,document_kind TEXT,note TEXT,status TEXT NOT NULL DEFAULT 'pending',created_at TIMESTAMPTZ DEFAULT now());\`);
const videoUpload=multer({dest:uploadDir,limits:{fileSize:500*1024*1024},fileFilter:(_req,file,cb)=>{const ok=['video/mp4','video/webm','video/quicktime','video/x-matroska'].includes(file.mimetype);cb(ok?null:new Error('فرمت ویدئو باید MP4، WebM، MOV یا MKV باشد'),ok)}});
app.post('/api/admin/course-videos',auth,admin,videoUpload.single('video'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'فایل ویدئوی آموزشی را انتخاب کنید'});const productId=Number(req.body.productId);if(!productId)return res.status(400).json({message:'دوره مشخص نشده است'});const p=await db('SELECT id,type FROM products WHERE id=$1',[productId]);if(!p.rowCount)return res.status(404).json({message:'دوره پیدا نشد'});if(p.rows[0].type!=='course')return res.status(400).json({message:'این محصول از نوع دوره آموزشی نیست'});const url='/uploads/'+req.file.filename;res.status(201).json({ok:true,url,originalName:req.file.originalname,size:req.file.size,mimeType:req.file.mimetype})}catch(e){if(req.file?.path)try{fs.unlinkSync(req.file.path)}catch{}res.status(500).json({message:'آپلود ویدئوی آموزشی ناموفق بود',detail:e.message})}});
app.post('/api/admin/digital-assets',auth,admin,upload.single('zip'),async(req,res)=>{try{const productId=Number(req.body.productId);const kind=req.body.kind==='source_code'?'source_code':'zip';const code=String(req.body.sourceCode||'');if(!productId)return res.status(400).json({message:'محصول دیجیتال مشخص نشده است'});if(kind==='zip'&&!req.file)return res.status(400).json({message:'برای محصول دیجیتال فایل ZIP را انتخاب کنید'});if(kind==='source_code'&&!code.trim())return res.status(400).json({message:'کد برنامه‌نویسی را وارد کنید'});const p=await db('SELECT id,type FROM products WHERE id=$1',[productId]);if(!p.rowCount)return res.status(404).json({message:'محصول پیدا نشد'});if(p.rows[0].type!=='digital_asset')return res.status(400).json({message:'این محصول از نوع دیجیتال نیست'});const url=req.file?'/uploads/'+req.file.filename:null;const r=await db('INSERT INTO digital_assets(product_id,file_url,original_name,file_size,asset_kind,source_code) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(product_id) DO UPDATE SET file_url=EXCLUDED.file_url,original_name=EXCLUDED.original_name,file_size=EXCLUDED.file_size,asset_kind=EXCLUDED.asset_kind,source_code=EXCLUDED.source_code RETURNING *',[productId,url,req.file?.originalname||null,req.file?.size||null,kind,kind==='source_code'?code:null]);await db('UPDATE products SET digital_asset_url=$1 WHERE id=$2',[url||'/api/digital-assets/'+productId,productId]);res.json({ok:true,asset:r.rows[0]})}catch(e){res.status(500).json({message:'ذخیره فایل دیجیتال ناموفق بود',detail:e.message})}});
app.get('/api/admin/digital-assets',auth,admin,async(_req,res)=>res.json((await db('SELECT * FROM digital_assets ORDER BY id DESC')).rows));
app.get('/api/digital-assets/:productId',auth,async(req,res)=>{try{const e=await db('SELECT 1 FROM enrollments WHERE user_id=$1 AND product_id=$2 AND status=$3',[req.user.id,req.params.productId,'active']);if(!e.rowCount&&req.user.role!=='admin')return res.status(403).json({message:'دسترسی فایل هنوز فعال نشده است'});const r=await db('SELECT * FROM digital_assets WHERE product_id=$1',[req.params.productId]);if(!r.rowCount)return res.status(404).json({message:'فایل دیجیتال هنوز اضافه نشده است'});res.json({asset:r.rows[0]})}catch(e){res.status(500).json({message:'خطای دریافت فایل دیجیتال'})}});
app.post('/api/student/documents',auth,upload.single('document'),async(req,res)=>{try{if(!req.file)return res.status(400).json({message:'فایل مدرک را انتخاب کنید'});const allowed=['image/jpeg','image/png','image/webp','application/pdf'];if(!allowed.includes(req.file.mimetype))return res.status(400).json({message:'فرمت مدرک باید PDF یا تصویر باشد'});const r=await db('INSERT INTO student_documents(user_id,file_url,original_name,document_kind,note) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.user.id,'/uploads/'+req.file.filename,req.file.originalname,String(req.body.kind||'مدرک دانش‌آموز'),String(req.body.note||'')]);res.status(201).json(r.rows[0])}catch(e){res.status(500).json({message:'ذخیره مدرک ناموفق بود',detail:e.message})}});
app.get('/api/admin/student-documents',auth,admin,async(_req,res)=>res.json((await db('SELECT d.*,u.first_name,u.last_name,u.username,u.phone FROM student_documents d JOIN users u ON u.id=d.user_id ORDER BY d.id DESC')).rows));
app.post('/api/admin/student-documents/:id/status',auth,admin,async(req,res)=>res.json((await db('UPDATE student_documents SET status=$1 WHERE id=$2 RETURNING *',[String(req.body.status||'reviewed'),req.params.id])).rows[0]));
app.get('/api/orders/:id/payment-details',auth,async(req,res)=>{const r=await db('SELECT id,total_amount,status,created_at FROM orders WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(!r.rowCount)return res.sendStatus(404);res.json({orderId:r.rows[0].id,exactAmount:r.rows[0].total_amount,status:r.rows[0].status,currency:'تومان',card:'6219-8619-5696-0073',bank:'بلو بانک',owner:'امیرعلی رضی خادمی'})});
app.post('/api/admin/state-sync',auth,admin,async(req,res)=>{try{const state=req.body?.state||{};await db('INSERT INTO app_settings(key,value,updated_at) VALUES($1,$2,now()) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,updated_at=now()',['frontend_state',JSON.stringify(state)]);res.json({ok:true,savedAt:new Date().toISOString(),keys:Object.keys(state)})}catch(e){res.status(500).json({message:'ذخیره مرکزی اطلاعات ناموفق بود',detail:e.message})}});
app.get('/api/admin/state-sync',auth,admin,async(_req,res)=>{const r=await db('SELECT value,updated_at FROM app_settings WHERE key=$1',['frontend_state']);res.json(r.rows[0]||{value:{},updated_at:null})});
`;
if (!source.includes("/api/admin/course-videos")) {
  source = source.replace("app.get('/api/health'", featureRoutes + "app.get('/api/health'");
}
await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
